apiVersion: v1
kind: Pod
metadata:
  labels:
    run: myapp1
  name: myapp1
  namespace: skillfied
spec:
  containers:
  - image: 933538/repo2026:nginx-v1.0
    name: myapp1
    resources:
      limits:
        cpu: "500m"
        memory: "256Mi"
      requests:
        cpu: "250m"
        memory: "128Mi"
    ports:
      - containerPort: 80    
  restartPolicy: Always
